spring:
  application:
    name: order-ws
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password: sa
server:
  port: 8081
  
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'